---
title: "L&T PxV Measurement invariance"
author: John Flournoy
date: `Sys.Date()`
output: 
  html_document:
    toc: true
    toc_float: true
---



```{r}
library(tidyverse)
lnt_df <- haven::read_sav('/data/jflournoy/lnt_pxvx/LT_wideAGT1234.sav')
lnt_df_nat <- dplyr::filter(lnt_df, aSubsample == 1)

create_scoring_frame <- function(items, rev_pattern = '.*x$', 
                                 sub_pattern = '^[abcd](.*?)x*$', 
                                 sub_replacement = '\\1',
                                 subscale_name = NULL)
{
  scoring_vec <- -2*as.numeric(grepl(rev_pattern, items))+1
  new_items <- gsub(pattern = sub_pattern, replacement = sub_replacement, items)
  scoring_df <- data.frame(item = new_items, scoring = scoring_vec,
                           stringsAsFactors = FALSE)
  if(!is.null(subscale_name)){
    scoring_df$subscale <- subscale_name
  }
  return(scoring_df)
}

#Some regex help munging the code from SPSS
# (\wbfi\d+x*)(?:\W+\+\W*)*
# '\1'
#
# compute (\w+) = 100\*\(mean(\(.*?\)) - 1\) */ *\d\. 
# \1 <- create_scoring_frame(\n  c\2\n  subscale_name = '\1')
#
# val_cols <- c('aspfin',
#               'BFA_MT',
#               'HRZ_COL',
#               'HRZ_IND',
#               'MVI_POMP',
#               'USI',
#               'VRT_COL',
#               'VRT_IND')

lnt_scales_list <- list(
  bfi_s_scale = create_scoring_frame(
    c('abfi32', 'abfi7', 'abfi42', 'abfi33', 'abfi13', 'abfi51', 'abfi37x',
      'abfi8x', 'abfi2x', 'abfi12x', 'abfi47x', 'abfi49x'),
    subscale_name = 'bfi_s_scale'),
  bfi_d_scale = create_scoring_frame(
    c('abfi26', 'abfi36', 'abfi16', 'abfi31x', 'abfi11', 'abfi5', 'abfi25', 'abfi20', 'abfi39x'),
    subscale_name = 'bfi_d_scale'),
  bfi_hp8 = create_scoring_frame(
    c('abfi45x', 'abfi46x', 'abfi47x', 'abfi48x', 'abfi49x', 'abfi50', 'abfi51', 'abfi52'), 
    subscale_name = 'bfi_hp8'),
  bfi_c = create_scoring_frame(
    c('abfi3', 'abfi8x', 'abfi13', 'abfi18x', 'abfi23x', 'abfi28', 'abfi33', 'abfi38', 'abfi43x'), 
    subscale_name = 'bfi_c'),
  bfi_a = create_scoring_frame(
    c('abfi2x', 'abfi7', 'abfi12x', 'abfi17', 'abfi22', 'abfi27x', 'abfi32', 'abfi37x', 'abfi42'), 
    subscale_name = 'bfi_a'),
  bfi_a6 = create_scoring_frame(
    c('abfi55', 'abfi56', 'abfi57', 'abfi58x', 'abfi59x', 'abfi60x', 'abfi61x', 'abfi62x'), 
    subscale_name = 'bfi_a6'),
  bfi_e = create_scoring_frame(
    c('abfi1', 'abfi6x', 'abfi11', 'abfi16', 'abfi21x', 'abfi26', 'abfi31x', 'abfi36'), 
    subscale_name = 'bfi_e'),
  bfi_n = create_scoring_frame(
    c('abfi4', 'abfi9x', 'abfi14', 'abfi19', 'abfi24x', 'abfi29', 'abfi34x', 'abfi39'), 
    subscale_name = 'bfi_n'),
  bfi_o = create_scoring_frame(
    c('abfi5', 'abfi10', 'abfi15', 'abfi20', 'abfi25', 'abfi30', 'abfi35x', 'abfi40', 'abfi41x', 'abfi44'), 
    subscale_name = 'bfi_o'),
  bfas_ac = create_scoring_frame(
    c('bbfas20x', 'bbfas21', 'bbfas22', 'bbfas23x', 'bbfas24', 
      'bbfas25x', 'bbfas26x', 'bbfas27', 'bbfas28x', 'bbfas29'),
    subscale_name = 'bfas_ac'),
  bfas_ap = create_scoring_frame(
    c('bbfas30', 'bbfas31x', 'bbfas32', 'bbfas33x', 'bbfas34', 
      'bbfas35', 'bbfas36x', 'bbfas37x', 'bbfas38x', 'bbfas102x'),
    subscale_name = 'bfas_ap'),
  bfas_ci = create_scoring_frame(
    c('bbfas40', 'bbfas41x', 'bbfas42x', 'bbfas43x', 'bbfas44', 
      'bbfas45x', 'bbfas46', 'bbfas47', 'bbfas48x', 'bbfas49x'),
    subscale_name = 'bfas_ci'),
  bfas_co = create_scoring_frame(
    c('bbfas50x', 'bbfas51', 'bbfas52', 'bbfas53', 'bbfas54x', 
      'bbfas55', 'bbfas56x', 'bbfas57x', 'bbfas58', 'bbfas59'),
    subscale_name = 'bfas_co'),
  bfas_ea = create_scoring_frame(
    c('bbfas70', 'bbfas71', 'bbfas72x', 'bbfas73', 'bbfas74x', 
      'bbfas75', 'bbfas76', 'bbfas77x', 'bbfas78', 'bbfas79x'),
    subscale_name = 'bfas_ea'),
  bfas_ee = create_scoring_frame(
    c('bbfas60', 'bbfas61x', 'bbfas62x', 'bbfas63x', 'bbfas64', 
      'bbfas65x', 'bbfas66x', 'bbfas67', 'bbfas68', 'bbfas69'),
    subscale_name = 'bfas_ee'),
  bfas_nv9 = create_scoring_frame(
    c('bbfas1x', 'bbfas2', 'bbfas3x', 'bbfas4', 'bbfas5x', 
      'bbfas6', 'bbfas7x', 'bbfas8', 'bbfas9'),
    subscale_name = 'bfas_nv9'),
  bfas_nv = create_scoring_frame(
    c('bbfi58', 'bbfas1x', 'bbfas2', 'bbfas3x', 'bbfas4', 
      'bbfas5x', 'bbfas6', 'bbfas7x', 'bbfas8', 'bbfas9'),
    subscale_name = 'bfas_nv'),
  bfas_nw = create_scoring_frame(
    c('bbfas10x', 'bbfas11', 'bbfas12x', 'bbfas13', 'bbfas14x', 
      'bbfas15', 'bbfas16', 'bbfas17x', 'bbfas18', 'bbfas19'),
    subscale_name = 'bfas_nw'),
  bfas_oi = create_scoring_frame(
    c('bbfas80', 'bbfas81x', 'bbfas82', 'bbfas83', 'bbfas84x', 
      'bbfas85x', 'bbfas86', 'bbfas87', 'bbfas88x', 'bbfas89'),
    subscale_name = 'bfas_oi'),
  bfas_oo = create_scoring_frame(
    c('bbfas90', 'bbfas91', 'bbfas92', 'bbfas93', 'bbfas94x', 
      'bbfas95', 'bbfas96', 'bbfas97x', 'bbfas98x', 'bbfas99x'),
    subscale_name = 'bfas_oo'),
  aspfin = create_scoring_frame(
    c('basp12', 'basp13', 'basp14', 'basp15', 'basp16'),
    subscale_name = 'aspfin'),
  bfa_mt = create_scoring_frame(
    c('abfas105', 'abfas106', 'abfas107x', 'abfas108x', 'abfas109', 'abfas110', 'abfas111x', 
      'abfas112x', 'abfas113', 'abfas114', 'abfas115', 'abfas116x', 'abfas117x', 'abfas118x'),
    subscale_name = 'bfa_mt'),
  hrz_ind = create_scoring_frame(
    c('aind1', 'aind2', 'aind3', 'aind4'),
    subscale_name = 'hrz_ind'),
  hrz_col = create_scoring_frame(
    c('aind9', 'aind10', 'aind11', 'aind12'),
    subscale_name = 'hrz_col'),
  mvi = create_scoring_frame(
    c('aval7', 'aval9', 'aval11', 'aval13', 'aval15', 'aval17', 'aval18', 'aval20', 'aval21', 
      'aval23', 'aval8x', 'aval10x', 'aval12x', 'aval14x', 'aval16x', 'aval19x', 'aval22x'),
    subscale_name = 'mvi'),
  usi = create_scoring_frame(
    c('ausi1', 'ausi2x', 'ausi3x', 'ausi5', 'ausi6x', 'ausi7'),
    subscale_name = 'usi'),
  vrt_ind = create_scoring_frame(
    c('aind5', 'aind6', 'aind7', 'aind8'),
    subscale_name = 'vrt_ind'),
  vrt_col = create_scoring_frame(
    c('aind13', 'aind14', 'aind15', 'aind16'),
    subscale_name = 'vrt_col'))

lnt_scales_df <- do.call(dplyr::bind_rows, lnt_scales_list)
```


```{r}
item_regexs <- paste0('^[abcd](',
                      paste(unique(lnt_scales_df$item), 
                            collapse = '|'),
                      ')$')

lnt_items_nat <- dplyr::select(lnt_df_nat, matches(item_regexs))

create_wave_keys <- function(scoring_df, wave_prefix = 'a'){
  scoring_df_w <- tidyr::spread(scoring_df, subscale, scoring, fill = 0)
  rownames(scoring_df_w) <- paste0(wave_prefix, scoring_df_w$item)
  scoring_df_w <- scoring_df_w[,-1]
  wave_keys <- psych::keys2list(scoring_df_w)
  return(wave_keys)
}

wave1_keys <- create_wave_keys(lnt_scales_df, 'a')
wave1_scored <- psych::scoreItems(keys = wave1_keys, lnt_items_nat)
wave2_keys <- create_wave_keys(lnt_scales_df, 'b')
wave2_scored <- psych::scoreItems(keys = wave2_keys, lnt_items_nat)
wave3_keys <- create_wave_keys(lnt_scales_df, 'c')
wave3_scored <- psych::scoreItems(keys = wave3_keys, lnt_items_nat)
wave4_keys <- create_wave_keys(lnt_scales_df, 'd')
wave4_scored <- psych::scoreItems(keys = wave4_keys, lnt_items_nat)

wave1_scored
wave2_scored
wave3_scored
wave4_scored
```

Create a function that will generate lavaan syntax for a scale

```{r}
library(lavaan)
library(semTools)
check_manifests_exist <- function(manifest_vec, aDF){
  df_names <- names(aDF)
  wave_manifest_names <- unlist(lapply(c('a', 'b', 'c', 'd'), paste0, manifest_vec))
  all_in_df_names <- all(wave_manifest_names %in% df_names)
  return(all_in_df_names)
}

create_lav_id_strat_widaman <- function(factor_name){
  factor_name_w1 <- paste0(factor_name, '_W1')
  factor_intercept <- paste0(factor_name_w1, ' ~ 0*1')
  factor_var <- paste0(factor_name_w1, ' ~~ 1*', factor_name_w1)
  paste0(factor_intercept, '\n', factor_var)
}

create_lav_factor_loadings <- function(factor_name, manifest_vec, group_equal = F){
  wave_factors <- paste0(factor_name, '_W', 1:4)
  num_indicators <- length(manifest_vec)
  load_labels <- lapply(paste0('L', 1:num_indicators),
                        function(label){
                          rep_labs <- rep(label, 4)
                          if(!group_equal){
                            rep_labs <- paste0(rep_labs, letters[1:4])
                          }
                          paste0('c(', paste(rep_labs, collapse = ', '), ')')
                        })
  loadings <- c(paste0(load_labels, '*'))
  wave_manifests_rhs <- lapply(c('a', 'b', 'c', 'd'),
                           function(letter){
                             paste(paste0(loadings,
                                          letter, 
                                          manifest_vec),
                                   collapse = ' + ')
                           })
  wave_eqs <- paste0(wave_factors, ' =~ ', wave_manifests_rhs)
  all_wave_model <- paste(wave_eqs, collapse = '\n')
  return(all_wave_model)
}

create_lav_ints <- function(manifest_vec, group_equal = F){
  int_grp_eqs <- lapply(manifest_vec, function(man_var){
    int_label <- paste0('int_', which(manifest_vec == man_var))
    grp_labels <- rep(int_label, 4)
    if(!group_equal){
      grp_labels <- paste0(grp_labels, 'g', 1:4)
    }
    grp_labels_collapsed <- paste(grp_labels, collapse = ', ')
    eq_rhs <- paste0('c(', grp_labels_collapsed, ')*1')
    eq_lhs <- paste0(letters[1:4], man_var)
    eq <- paste0(eq_lhs, ' ~ ', eq_rhs)
    paste(eq, collapse = '\n')
  })
  int_all_eqs <- paste(int_grp_eqs, collapse = '\n\n')
  return(int_all_eqs)
}

create_lav_resid_var <- function(manifest_vec, group_equal = F){
  var_grp_eqs <- lapply(manifest_vec, function(man_var){
    var_label <- paste0('v_', which(manifest_vec == man_var))
    grp_labels <- rep(var_label, 4)
    if(!group_equal){
      grp_labels <- paste0(grp_labels, 'g', 1:4)
    }
    grp_labels_collapsed <- paste(grp_labels, collapse = ', ')
    eq_rhs <- paste0('c(', grp_labels_collapsed, ')')
    eq_lhs <- paste0(letters[1:4], man_var)
    eq <- paste0(eq_lhs, ' ~~ ', eq_rhs, '*', eq_lhs)
    paste(eq, collapse = '\n')
  })
  var_all_eqs <- paste(var_grp_eqs, collapse = '\n\n')
  return(var_all_eqs)
}

create_lav_resid_covar <- function(manifest_vec, group_equal = F){
  covar_grp_eqs <- lapply(manifest_vec, function(man_var){
    lag_distances <- unlist(lapply(3:1, function(x) seq(from = 1, to = x, by = 1)))
    var_label <- paste0('cv_', which(manifest_vec == man_var), lag_distances)
    grp_labels_collapsed <- lapply(var_label, function(alab){
      thelabs <- rep(alab, 4)
      if(!group_equal){
        thelabs <- paste0(thelabs, 'g', 1:4)
      }
      thelabs_collapsed <- paste(thelabs, collapse = ', ')
      return(thelabs_collapsed)
    })
    connectors <- paste0(' ~~ c(', grp_labels_collapsed, ')*')
    wave_vars <- paste0(letters[1:4], man_var)
    covar_label_matrix <- combn(wave_vars, 2)
    eqs <- paste0(covar_label_matrix[1,], connectors, covar_label_matrix[2,])
    eqs_collapsed <- paste(eqs, collapse = '\n')
    return(eqs_collapsed)
  })
  covar_grp_eqs_all <- paste(covar_grp_eqs, collapse = '\n\n')
  return(covar_grp_eqs_all)
}

create_lav_invariance_model <- function(factor_name, manifest_vec, type = c('baseline','metric','strong', 'strict')){
  #Baseline: strict longitudinal invariance with added constraint that
  #covariance of residuals across the same lag distnace should be the same.
  #Metric: factor loadings equal across groups.
  #Strong: intercepts equal across groups.
  #Strict: residual variances are equal across groups.
  
  amod <- switch(type,
                 baseline = paste(c(create_lav_id_strat_widaman(factor_name),
                                   create_lav_factor_loadings(factor_name, manifest_vec, group_equal = F),
                                   create_lav_ints(manifest_vec, group_equal = F),
                                   create_lav_resid_var(manifest_vec, group_equal = F),
                                   create_lav_resid_covar(manifest_vec, group_equal = F)), 
                                 collapse = '\n\n#---\n\n'),
                 metric = paste(c(create_lav_id_strat_widaman(factor_name),
                                   create_lav_factor_loadings(factor_name, manifest_vec, group_equal = T),
                                   create_lav_ints(manifest_vec, group_equal = F),
                                   create_lav_resid_var(manifest_vec, group_equal = F),
                                   create_lav_resid_covar(manifest_vec, group_equal = F)), 
                                 collapse = '\n\n#---\n\n'),
                 strong = paste(c(create_lav_id_strat_widaman(factor_name),
                                   create_lav_factor_loadings(factor_name, manifest_vec, group_equal = T),
                                   create_lav_ints(manifest_vec, group_equal = T),
                                   create_lav_resid_var(manifest_vec, group_equal = F),
                                   create_lav_resid_covar(manifest_vec, group_equal = F)), 
                                 collapse = '\n\n#---\n\n'),
                 strict = paste(c(create_lav_id_strat_widaman(factor_name),
                                   create_lav_factor_loadings(factor_name, manifest_vec, group_equal = T),
                                   create_lav_ints(manifest_vec, group_equal = T),
                                   create_lav_resid_var(manifest_vec, group_equal = T),
                                   create_lav_resid_covar(manifest_vec, group_equal = F)), 
                                 collapse = '\n\n#---\n\n'))
  return(amod)
}

get_subscale_items <- function(scoring_df, subscale){
  scoring_df$item[scoring_df$subscale == subscale]
}

sem_invar <- function(model, data, ...){
  fit <- lavaan(model = model, data = data,
                int.lv.free = T,
                auto.fix.first = F,
                int.ov.free = TRUE, 
                auto.var = TRUE, 
                auto.cov.lv.x = TRUE,
                auto.cov.y = TRUE,
                ...)
  return(fit)
} 

run_invariance_model <- function(factor_name, manifest_vec, item_data, type = 'baseline', group, ...){
  an_invar_model <- create_lav_invariance_model(factor_name, manifest_vec, type = type)
  a_fit <- sem_invar(model = an_invar_model, 
                     data = item_data,
                     group = group, 
                     ...)
  return(a_fit)
}

run_invariance_tests <- function(factor_name, manifest_vec, item_data, fit_measures, group, ...){
  require(future)
  require(future.apply)
  all_invar_types <- c('baseline','metric','strong', 'strict')
  invar_models <- future_lapply(all_invar_types,
                                function(type){
                                  run_invariance_model(factor_name, 
                                                       manifest_vec, 
                                                       item_data, 
                                                       type = type, 
                                                       group = group, 
                                                       ...)
                                })
}

lnt_df_nat_decades <- dplyr::filter(lnt_df_nat, aage < 60, aage >= 20) 
lnt_df_nat_decades$decade_group <- factor(lnt_df_nat_decades$aage %/% 10, levels = c(2, 3, 4, 5), labels = c('20s', '30s', '40s', '50s'))
lnt_df_nat_decades$agender <- as_factor(lnt_df_nat_decades$agender)
lnt_nat_decades_items <- dplyr::select(lnt_df_nat_decades, matches(item_regexs), decade_group, agender)
length(unique(lnt_df_nat_decades$subjid))

these_items <- get_subscale_items(lnt_scales_df, 'bfi_e')
check_manifests_exist(these_items, lnt_nat_decades_items)

bfi_e_model.bl <- create_lav_invariance_model('bfi_e', these_items, type = 'baseline')
bfi_e.bl <- sem_invar(model = bfi_e_model.bl, 
                data = lnt_nat_decades_items,  
                missing = 'fiml', 
                group = 'decade_group')
summary(bfi_e.bl, standardized = T)

bfi_e_model.metric <- create_lav_invariance_model('bfi_e', these_items, type = 'metric')
bfi_e.metric <- sem_invar(model = bfi_e_model.metric, 
                data = lnt_nat_decades_items,  
                missing = 'fiml', 
                group = 'decade_group')
summary(bfi_e.metric, standardized = T)

bfi_e_model.strong <- create_lav_invariance_model('bfi_e', these_items, type = 'strong')
bfi_e.strong <- sem_invar(model = bfi_e_model.strong, 
                data = lnt_nat_decades_items,  
                missing = 'fiml', 
                group = 'decade_group')
summary(bfi_e.strong, standardized = T)

bfi_e_model.strict <- create_lav_invariance_model('bfi_e', these_items, type = 'strict')
bfi_e.strict <- sem_invar(model = bfi_e_model.strict, 
                data = lnt_nat_decades_items,  
                missing = 'fiml', 
                group = 'decade_group')
summary(bfi_e.strict, standardized = T)

these_fit_measures <- c('cfi', 
                        'rmsea', 'rmsea.ci.lower', 'rmsea.ci.upper')

(lrt_thing <- lavTestLRT(bfi_e.bl, bfi_e.metric, bfi_e.strong, bfi_e.strict))
(fit_list <- rbind(bfi_e.bl = fitmeasures(bfi_e.bl, fit.measures = these_fit_measures), 
                   bfi_e.metric = fitmeasures(bfi_e.metric, fit.measures = these_fit_measures), 
                   bfi_e.strong = fitmeasures(bfi_e.strong, fit.measures = these_fit_measures),
                   bfi_e.strict = fitmeasures(bfi_e.strict, fit.measures = these_fit_measures)))
dplyr::select(
  dplyr::mutate(
    as_data_frame(fit_list),
    cfi = round(cfi, 3),
    rmsea = paste0(round(rmsea, 3), ' [',
                   round(rmsea.ci.lower, 3), ', ',
                   round(rmsea.ci.upper, 3), ']')),
  cfi, rmsea)

```

```{r}

# process in parallel, 2 cores for the trait level, and 4 cores inside each for the models to fit
#plan(list(tweak(multiprocess, workers = 2), tweak(multiprocess, workers = 4)))